### PR TITLE
Overwrite docker-compose.yml

### PR DESCRIPTION
**Pull request by jburel**
Add ability to modify the configuration parameter
This is required by https://github.com/ome/omero-cli-transfer

cc @joshmoore @erickmartins

### CODE REVIEW

**Comment by joshmoore** [comment]
I'm a little worried that overwriting the file entirely will lead to a brittle system, since there's no knowing what might happen upstream in the future. My ideal case would be a way to just inject environment variables, but we'd need to look into that. A quicker fix might be *extending* the compose file as is done in https://github.com/ome/omero-test-infra/blob/421c3aeb9861fcdce1f29f815c425f877de50159/volumes.yml#L4 which, e.g., is used by imagej-omero's testing: https://github.com/imagej/imagej-omero/blob/master/.github/test.sh#L28

**Comment by jburel** [comment]
I have added the option to specify the variable. This should allow to change the configuration without overwriting the ``docker-compose`` file

**Comment by joshmoore** [comment]
@jburel, have you tried the new-ish [`env_file`](https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute) property? Reading the docs, it looks like we could additionally have an env file just for the server element and then define the CONFIG_ style properties without relisting them explicitly:

```
CONFIG_omero_policy_binary__access=+read,+write,+image
```

**Comment by jburel** [comment]
I have not. I will look at it

**Comment by jburel** [comment]
I have tried various combination
``env_file`` and ``environment`` does not work
```
parsing /tmp/omero-app/.omero/docker-compose.yml: yaml: unmarshal errors:
  line 25: mapping key "build" already defined at line 9
  line 29: mapping key "environment" already defined at line 14
  line 32: mapping key "ports" already defined at line 22
```
The case I thought could be interesting for our case
``env_file:
  - path: ./default.env
    required: true # default
  - path: ./override.env
    required: false
``
leads to 
```
validating /tmp/omero-app/.omero/docker-compose.yml: services.omero.env_file.0 must be a string
```

So I think we should, for now, keep the working approach implemented in the PR and revisit afterwards.

**Comment by joshmoore** [comment]
Sounds like it may be a docker-compose file format version issue.

**Comment by jburel** [comment]
I use version: "3"

**Comment by jburel** [comment]
Discussed with @joshmoore today, we merge this PR to unlock [omero-cli-transfer](https://github.com/ome/omero-cli-transfer/pull/75). We will revisit later on

**Pull request merged**
